name: Pre-release

permissions: read-all

on:
  workflow_dispatch:
  push:
    branches:
      - release-please-*

jobs:
  pre-release:
    name: 'Pre-release checks'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6 # v6.0.2
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v6 # v6.2.0
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Generate documents
        run: npm run docs

      - name: Run docs smoke check
        run: npm run docs:lint

      - name: Verify server.json
        run: npm run verify-server-json-version
